trigger:
  - master

pr:
 branches:
   include:
     - master

variables:
  solutionFile : '$(Build.SourcesDirectory)\Src\NewtonsoftExtensions.sln'
  configuration: 'release'

pool:
  vmImage: 'windows-latest'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud-Public'
    organization: 'cloudndevops'
    scannerMode: 'MSBuild'
    projectKey: 'Newtonsoft.Extensions'
    projectName: 'Newtonsoft.Extensions'
    extraProperties: 'sonar.cs.vscoveragexml.reportsPaths = $(Build.SourceDirectory)\**\*.coverage'

- task: DotNetCoreCLI@2
  displayName: Restore NuGet Packages
  inputs:
    command: restore
    projects: $(solutionFile)

- task: DotNetCoreCLI@2
  displayName: Build Solution
  inputs:
    command: build
    projects: $(solutionFile)
    configuration: $(configuration)
    arguments: --no-restore

- task: DotNetCoreCLI@2
  displayName: Execute Test Cases
  inputs:
    command: test
    projects: $(solutionFile)
    configuration: $(configuration)
    arguments: --no-build --collect:"Code Coverage"

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
