trigger:
  - master

variables:
  solutionFile : '$(Build.SourcesDirectory)/Src/NewtonsoftExtensions.sln'
  configuration: 'release'

stages:
- stage: Build
  jobs:
  - job: Build

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: restore
        projects: $(solutionFile)

    - task: DotNetCoreCLI@2
      inputs:
        command: build
        projects: $(solutionFile)
        arguments: --configuration $(configuration)