trigger:
  - master

pr:
 branches:
   include:
     - master

variables:
  solutionFile : '$(Build.SourcesDirectory)\Src\NewtonsoftExtensions.sln'
  configuration: 'release'

pool:
  vmImage: 'windows-latest'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud-CloudNDevOps'
    organization: 'cloudndevops'
    scannerMode: 'MSBuild'
    projectKey: 'Newtonsoft.Extensions'
    projectName: 'Newtonsoft.Extensions'
    extraProperties: 'sonar.cs.vstest.reportsPaths=$(System.DefaultWorkingDirectory)/TestResults/**/*.coverage'

- task: DotNetCoreCLI@2
  displayName: Restore NuGet Packages
  inputs:
    command: restore
    projects: $(solutionFile)

- task: DotNetCoreCLI@2
  displayName: Build Solution
  inputs:
    command: build
    projects: $(solutionFile)
    configuration: $(configuration)
    arguments: --no-restore

- task: DotNetCoreCLI@2
  displayName: Execute Test Cases
  inputs:
    command: 'test'
    projects: '$(solutionFile)'
    configuration: $(BuildConfiguration)
    nobuild: true
    arguments: '--collect:"Code Coverage" --settings .runsettings'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1

- task: DotNetCoreCLI@2
  displayName: Create NuGet Package
  inputs:
   command: pack
   projects: $(solutionFile)
   configuration: $(configuration)
   nobuild: true
   